version: '3.8'

services:
  app:
    image: proyecto-backend
    container_name: proyecto-backend
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod,logstash
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/proyecto
      - SPRING_DATASOURCE_USERNAME=proyecto
      - SPRING_DATASOURCE_PASSWORD=proyecto
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: proyecto-db
    environment:
      - POSTGRES_DB=proyecto
      - POSTGRES_USER=proyecto
      - POSTGRES_PASSWORD=proyecto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
